name: Hellow world workflow
on:
  push:
    branches:
      - test1
  pull_request:
    branches:
      - test1
  workflow_dispatch: null
jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Run Python script
        run: python test.py
