---
name: Hellow world workflow
on:
  push:
    branches:
      - test1
  pull_request:
    branches:
      - test1
  workflow_dispatch: null
jobs:
  hi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hi world
        run: echo "hi world"
        shell: bash
      run: test.py
