name: Hellow world workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name : hello world
      run: echo "Hello world"
      shell: bash
    - name: Upload files to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --exclude '.git/*'
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
